### ISSUE TITLE
Fix the crash caused by when you deal 10 or more ion damage in a single hit to a un-ionized system while having a manned sensors 3.

### ISSUE THREAD

**Issue by gabrielsubzero** [FTL-Hyperspace/FTL-Hyperspace#132]
Basically the game crashes rn if you can see a ion stack that's 10 or higher, it would be nice if it was fixed, preferably in a way that also shows ion stacks higher than 5, as rn there isn't a number for those so it's just blank iirc.

**Comment by Nasa62** [comment]
I do believe this is vanilla, as the game only has an array of images for 9 ion states, and it's hardcoded. It would probably require completely reverse engineering how ion rendering is handled in FTL.

**Comment by Nasa62** [comment]
Will be fixed by #161 when merged
