### ISSUE TITLE
Fix the crash that occurs when the ship doesn't have a shield system assigned and a overcharger drone trigger.

### ISSUE THREAD

**Issue by gabrielsubzero** [FTL-Hyperspace/FTL-Hyperspace#134]
Currently if you don't have a shield system assigned to a ship and a shield drone triggers the game will crash, not only that, not having shields also makes energy shields not work at all, i assume it's a vanilla bug but it's very annoying to work around imo.

**Comment by Nasa62** [comment]
This is probably because the ShieldSystem doesn't actually exist in that case, so it's calling a null value... are Shield drones a Hyperspace feature?

**Comment by ChronoVortex** [comment]
Fixed in https://github.com/FTL-Hyperspace/FTL-Hyperspace/pull/147
