### ISSUE TITLE
Auto choice broke my game

### ISSUE THREAD

**Issue by baweporink** [FTL-Hyperspace/FTL-Hyperspace#187]
Okay auto choice is broken. I don't have OpenGL, but auto-select tries to run FTL using OpenGL, which is why the game just doesn't start (use -directx don't work)

**Comment by Nasa62** [comment]
Please provide logs, GPU & system information.
We need:
- FTL.log
- FTL_HS.log
- GPU Manufacturer & Model information (e.g. "Nvidia RTX2070" or "Intel Arc A770")
- GPU Driver information (such as the output from `dxdiag`)
- System OS
- System RAM amount

**Comment by baweporink** [comment]
Oh, I'm sorry. I have already been answered in discord, but I forgot to close.
