### ISSUE TITLE
Show additional ship information in hangar: starting missiles, starting drone parts, locations of uninstalled systems

### ISSUE THREAD

**Issue by CommunistMountain** [FTL-Hyperspace/FTL-Hyperspace#196]
I wanted fuel as well but apparently it is a "start-of-run" thing like starting scrap so nevermind that.

**Comment by Nasa62** [comment]
I think a lot of this could be done with a mod already using Lua.
If there's something preventing a mod from drawing this information (such as a missing hook into the hangar page or something) then that might be a more specific request for a add of something into Hyperspace to allow it.

**Comment by CommunistMountain** [comment]
I just thought it would be nice if Hyperspace features it.

The first time I asked about the missing systems thing, Admiral Billy said he had a work in progress thing for it in ShipBuilderSystemToggle branch. He was also interested in adding the starting drones and missiles in hangar. That was like 1 year ago.

Well I don't expect him or anyone to do this with any urgency, just putting this suggestion here.

**Comment by Nasa62** [comment]
@Admiral-Billy any comment? 😅
