### ISSUE TITLE
[Normal FTL] "Could not find: font" in credits

### ISSUE THREAD

**Issue by desertprinter** [FTL-Hyperspace/FTL-Hyperspace#198]
![image](https://github.com/FTL-Hyperspace/FTL-Hyperspace/assets/67029981/295c119e-947b-46e4-8312-63ef2c3becf7)
Since it doesn't happen in Multiverse, this is prolly a Hyperspace.ftl issue
![IMG_0520](https://github.com/FTL-Hyperspace/FTL-Hyperspace/assets/67029981/be2af618-a547-4cb3-830c-24fe1a28ed8a)
(Had to use my phone because the credits are left if the keyboard is touched at all.)
(Also how did one photo end up a .PNG that I needed to crop, while another was a .JPEG that needed no cropping to fit into upload limits?)

**Comment by desertprinter** [comment]
...I don't know how to add labels, or if I'm even supposed to be the one to add them.

**Comment by desertprinter** [comment]
I’m not, apparently, got used to the suggestion and bug report forums back on the MV Discord I guess

**Comment by The-Dumb-Dino** [comment]
Can someone close this issue?
