### ISSUE TITLE
Artillery system rendering uses same image for different rooms

### ISSUE THREAD

**Issue by Nasa62** [FTL-Hyperspace/FTL-Hyperspace#20]
The Artillery system's room image isn't configurable.

This can lead to incorrect rendering when there is a combination of artillery rooms with different shapes/orientations.
![image](https://user-images.githubusercontent.com/1423894/170057630-a5fdf4b1-c20d-41df-9054-14bae054f572.png)

It would be nice if we had a way to configure the room image.

**Comment by porcu93** [comment]
A quick temporary fix you can use if by setting the roomAnim with renderLayer set to 1 in the different artillery rooms while having the actual room image be blank.

**Comment by Nasa62** [comment]
I can easily make the room image blank by affecting something like:
```lua
Hyperspace.ships.player.artillerySystems[1].interiorImage -- Artillery System #2
```

But I was hoping to load a different image in its place, I've been playing around with this:
```lua
Hyperspace.ships.player.artillerySystems[1].interiorImage = Hyperspace.Resources:CreateImagePrimitiveString("img/ship/interior/room_battery_orchid_2.png", 0, 0, 0, Graphics.GL_Color(1.0, 1.0, 1.0, 0.75), 1.0, false)
```
As an example but I don't know if my string to the filename is just wrong and not what CreateImagePrimitiveString expects or not. So far it just results in an empty image and in nothing in that room rendering.

**Comment by SafalChapagain** [comment]
You need to omit the `img/` from the filename, it’s prefixed with that automatically.

**Comment by SafalChapagain** [comment]
You need to omit the `img/` from the string, it gets prefixed with that.

**Comment by Nasa62** [comment]
Yeah I had tried that as
```lua
Hyperspace.ships.player.artillerySystems[1].interiorImage = Hyperspace.Resources:CreateImagePrimitiveString("ship/interior/room_battery_orchid_2.png", 0, 0, 0, Graphics.GL_Color(1.0, 1.0, 1.0, 0.75), 1.0, false)
```
And it still wasn't doing what I wanted, so maybe I need something for the X & Y values of CreateImagePrimitiveString?

**Comment by porcu93** [comment]
What I meant with my suggestion is something you do in the hyperspace.xml.append of your mod.

**Comment by Nasa62** [comment]
Could you provide an example? Because this is something Kix was complaining about in Multiverse.

**Comment by porcu93** [comment]
Sure thing, here's a quick image made with paint of what I suggested doing, may need some tweaking given that the images don't change when O2 is low
![Different Artillery rooms](https://user-images.githubusercontent.com/6943468/170469386-c331cfe4-ff08-4807-a290-a9a3aea56dd9.png)

**Comment by porcu93** [comment]
Set the renderLayer in that portion of code to 0 and it should go below the O2

**Comment by mathchamp93** [comment]
renderLayer 0 goes on top of OnRenderFloor (so probably floor image)
renderLayer 1 goes right underneath breaches
renderLayer 2 goes right under hacking sparks
renderLayer 3 and 4 go over everything, 3 needs the room to be visible (whether it's blacked out or not) while 4 does not

So you probably want 0.

**Comment by Nasa62** [comment]
Great, so I guess Kix & the MV team can just do this instead.
