### ISSUE TITLE
hyperspace error

### ISSUE THREAD

**Issue by ToasterCat1** [FTL-Hyperspace/FTL-Hyperspace#205]
whenever i try to launch ftl multiverse this error message pops up:

Error parsing <augments> in hyperspace.xml
Unrecognized stat boost name: cloneSpeedMultiplier

  then this:

Assertion failed!

Program: ...
File: C:\develop\GitHub\FTL-Hyperspace...\LuaLib...ipt.cpp
Line: 164

Expression:lua_isinteger(lua, 1)

For information on how your program can cause an assertion failure, see the Visual C++ documentaion on assets

(Press Retry to debug the application - JIT must be enabled)

  and this:

Assetion failed!

Program: ...
File: C:\develop\GitHub\FTL-Hyperspace...\LuaLib...ipt.cpp
Line: 167

Expression: callbackHookld > InternalEvents::UNKOWN

For information on how your program can cause an assertion failure, see the Visual C++ documentaion on assets

(Press Retry to debug the application - JIT must be enabled)

  any idea whats going on and how to fix it?

**Comment by Nasa62** [comment]
Did you build Hyperspace from source yourself? It's a bit odd to see `C:\develop` in the error.

**Comment by ToasterCat1** [comment]
my issue has been resolved. how do i say its not open anymore?
