### ISSUE TITLE
Custom Ship Icons on the Map depending on Player Ship

### ISSUE THREAD

**Issue by SilentStorm064** [FTL-Hyperspace/FTL-Hyperspace#25]
It would be great if there was the option to replace StarMap::ship and StarMap::shipNoFuel at the start of a run depending on what ship the player is using. That way you could have a unique icon for every player ship and not always the Kestrel.

![#####](https://user-images.githubusercontent.com/109462136/179394549-ebb9d8c2-dab7-402b-977f-8a466ff824d3.PNG)

**Comment by adaneslavo** [comment]
I guess image is from vanilla mod?

**Comment by SilentStorm064** [comment]
@adaneslavo The images are made by myself and as of yet unreleased. I would like to add them to the game with the requested feature, because if you want to use them right now you need to reinstall the correct version of the ship image every time as you start a new game, as the game has no built in logic to replace the map image depending on which ship you're playing.
