### ISSUE TITLE
Expose a method to upgrade/downgrade a ship's reactor

### ISSUE THREAD

**Issue by Choosechee** [FTL-Hyperspace/FTL-Hyperspace#260]
Right now, there's no way to upgrade or downgrade a ship's reactor in Lua. I don't even see a function that could do this in the FTLGame files.

**Comment by kokoro11** [comment]
I think there is? You can modify a ship's rector by the `PowerManager` class.
```lua
local powerMgr = Hyperspace.PowerManager.GetPowerManager(SHIP_ID)
powerMgr.currentPower.second = powerMgr.currentPower.second + DELTA
```

**Comment by Choosechee** [comment]
> I think there is? You can modify a ship's rector by the `PowerManager` class.
> 
> ```lua
> local powerMgr = Hyperspace.PowerManager.GetPowerManager(SHIP_ID)
> powerMgr.currentPower.second = powerMgr.currentPower.second + DELTA
> ```

You're right, this works perfectly. Thank you!
