### ISSUE TITLE
Backup Battery hack crash

### ISSUE THREAD

**Issue by JerseeBeep** [FTL-Hyperspace/FTL-Hyperspace#299]
Suffering a hack on your Backup Battery when your reactor has 0 (and possibly still at 1 or 2) base power crashes your game. This is easily seen on Multiverse's Alt-Peacekeeper cruiser and the Limit 4.

**Comment by THETASOLA** [comment]
Fixed here https://github.com/FTL-Hyperspace/FTL-Hyperspace/pull/303
