### ISSUE TITLE
Saving and exiting the game while there is erosion damage being applied on screen prevents you from being able to load back in.

### ISSUE THREAD

**Issue by arcburnergit** [FTL-Hyperspace/FTL-Hyperspace#320]
I discovered this while modding MV, however I have tested this in vanilla hyperspace and it still breaks the game.
I will provide the mod I made for testing the bug, and a video of how I tested it.
When I didn't provide an animation for the erosion the bug didn't occur.
[ERODE_TEST.zip](https://github.com/user-attachments/files/16645090/ERODE_TEST.zip)

This issue is present both when saving and exiting the game entirely, and when returning to the main menu.
https://github.com/user-attachments/assets/709a343c-0bab-43e6-85d9-f17432820d92

**Comment by ChronoVortex** [comment]
Probably a mismatch between what's being saved and loaded in `RoomAnim::SaveState` and `RoomAnim::LoadState`
