### ISSUE TITLE
Contributing to this repo's wiki pages

### ISSUE THREAD

**Issue by C20H12** [FTL-Hyperspace/FTL-Hyperspace#36]
I composed a wiki page for the Lua `Graphics`  module. However there doesn't seem to be an option to open a pull request just for the wiki.  The only option is to clone the wiki and add the Markdown page manually.    

Link to the page:
https://github.com/C20H12/FTL-Hyperspace/wiki/Lua-Graphics-Module
Link to the wiki "repo":
https://github.com/C20H12/FTL-Hyperspace.wiki.git

Let me know if there are any problems, or that I need to make changes to the page

**Comment by Nasa62** [comment]
Thank you. I'll work on adding them.

Yeah Github doesn't have the ability to do pull requests for wikis, it's dumb when it can be done for literally everything else.

**Comment by C20H12** [comment]
Nice. Thanks

**Comment by Nasa62** [comment]
Added to the Wiki
