### ISSUE TITLE
FTL_JUMPER_GOOD should take FTL_JUMPER into account when calculating fuel costs

### ISSUE THREAD

**Issue by CommunistMountain** [FTL-Hyperspace/FTL-Hyperspace#362]
The first is easy and ought to be considered a bug to be fixed. The second is hard and just a suggestion so I don't expect you guys to implement it.

1. Use only 1 fuel when you also have FTL_JUMPER and are jumping to a previously visited beacon.
2. The fuel cost of jumping to an unvisited beacon also takes into account visited beacons having an effective distance of 1. E.g. if an unvisited beacon is 5 away but you have previously visited a beacon beside it, it costs 2.

**Comment by ChronoVortex** [comment]
What exactly is the issue? Is it using two fuel if you jump while you have both augments or something?
