### ISSUE TITLE
Hyperspace.ErrorMessage() doesn't show non-ASCII characters properly on Windows

### ISSUE THREAD

**Issue by nedsociety** [FTL-Hyperspace/FTL-Hyperspace#38]
### Symptom

Here's a part of the [Korean version of MV 5.3 lua script](https://github.com/ftl-mv-translation/ftl-mv-translation/blob/9e290c8f9bbae1f2cd81eded9004b0ea96283de2/auxfiles-ko/multiverse.lua#L260) (the lua file itself is encoded in utf-8):

```lua
function mods.multiverse.sheLost()
	Hyperspace.ErrorMessage("네가 나를 배신하다니 믿을 수 없어 배회자! 아주 좋았는데... 거의 완벽에 가까웠는데! 뭐, 그럼 어디 그 보잘 것 없는 해충들이 지배하는 무익하고 지루한 멀티버스에서 잘살아 보라고. >:(")
end
script.on_game_event("HER_FINALE_REAL", false, mods.multiverse.sheLost)
```

Here's the reported result from @dedor (not necessarily that event, but you get the point):

![image](https://user-images.githubusercontent.com/11943013/188509897-193c51c9-9f86-4776-b5bc-3ffbe60ae33a.png)

### Repro steps

1. Apply the aforementioned lua file to the MV 5.3 (or download the packaged Korean MV from [here](https://drive.google.com/drive/folders/1N7I6_p7aFBGchcuSyw0b3_WvdBLFJUlZ), it's a nightly package)
2. Use `EVENT HER_FINALE_REAL` to enter the event.
3. See the bajimoke message.

### Initial source probe

Currently Hyperspace passes the argument directly to the [`MessageBoxA()`](https://github.com/FTL-Hyperspace/FTL-Hyperspace/blob/01173cfdaed790993f58b09f49282d2ad1d50e76/Global.cpp#L70) call. I'm not exactly sure what encoding SWIG uses to translate lua strings into C++ strings. But I'm certain that if it tries to pass the UTF-8 strings into `~A` functions it won't work (unless you've set [this](https://stackoverflow.com/questions/56419639/what-does-beta-use-unicode-utf-8-for-worldwide-language-support-actually-do)).

With that in mind the call should be changed to `MessageBoxW()` with proper encoding conversion, possibly from either MBCS/UTF-8 to UTF-16 depending on the lua encoding.

**Comment by nedsociety** [comment]
Update: confirmed. It's UTF-8 strings:

![image](https://user-images.githubusercontent.com/11943013/188515864-705f1382-4573-452b-b3fe-4f4bf49b453c.png)

This happens when I apply [UTF-8 as ANSI](https://stackoverflow.com/questions/56419639/what-does-beta-use-unicode-utf-8-for-worldwide-language-support-actually-do) to my system locale. I do not know if lua treats all strings as UTF-8 internally, or if it's simply because of the fact that the lua source code file is encoded in UTF-8. In any case it might be safe to assume them to be always UTF-8 for the most cases, because if it's the latter we don't have easy way to deal with it anyway.

In that case we could use `MessageBoxW()` with a simple UTF-8 to UTF-16 conversion. [`utf_to_utf()` from `boost::locale::conv`](https://www.boost.org/doc/libs/1_80_0/libs/locale/doc/html/charset_handling.html) might work handy, or if we can tolerate memory leak, [`wstring_convert`](https://en.cppreference.com/w/cpp/locale/wstring_convert) can be used instead.

**Comment by head47** [comment]
I can confirm the Russian version is affected too.
![image](https://user-images.githubusercontent.com/63517545/188720493-84448358-ca2c-415f-b20b-ec5673700ea8.png)
