### ISSUE TITLE
Cloning bays cannot have the cabin rotated

### ISSUE THREAD

**Issue by adaneslavo** [FTL-Hyperspace/FTL-Hyperspace#57]
[UI fix]

Looks ugly, don't you think?
It's a problem since vanilla...

![obraz](https://user-images.githubusercontent.com/33016300/201209771-4c988288-5c8d-4cde-acf3-6cf24933ab19.png)

**Comment by Nasa62** [comment]
This isn't easy to fix, it might be something practical for someone to try to load a different image with Lua.
