### ISSUE TITLE
Make HP bar scale correctly

### ISSUE THREAD

**Issue by adaneslavo** [FTL-Hyperspace/FTL-Hyperspace#60]
[UI fix]

It's issue since vanilla, that cannot be solved with simple retexturing:
![obraz](https://user-images.githubusercontent.com/33016300/201468531-5c6ea1a4-59a3-4ac8-9a90-bb1f9165a297.png)
This pixel is annoying, don't you think :)?

**Comment by Nasa62** [comment]
What pixel? The fact it stops right before the little arch up?
![image](https://user-images.githubusercontent.com/1423894/202315641-366e44aa-35a8-45c6-80cd-817c4da09cbe.png)

Or are you talking about something else

**Comment by adaneslavo** [comment]
Bar is divided on 3 parts 10 hp each. But there is a piece of second part drawn after the break you highlighted. That yellow thing shouldn't be drawn.

**Comment by mathchamp93** [comment]
Mod can just move the gap between segments over by a pixel to the right. I don't think I've noticed anything like this with the vanilla textures.
