### ISSUE TITLE
expected 'Damage' got 'number'

### ISSUE THREAD

**Issue by Oman395** [FTL-Hyperspace/FTL-Hyperspace#61]
How on earth do I get access to the DamageParameter type? It's mentioned in most of the damaging ShipManager functions, but I can't figure out how to get actually use them becuase it gives me an error whenever I try to pass an amount of damage

**Comment by Oman395** [comment]
Figured it out! The wiki just doesn't have any information about Hyperspace.Damage. Below is some example code for how to use it, for anyone looking this up:
```lua
local damage = Hyperspace.Damage()
damage.iDamage = 1
Hyperspace.ships.player:DamageBeam(Hyperspace.ships.player:GetRandomRoomCenter(), Hyperspace.ships.player:GetRandomRoomCenter(), damage)
```
Seems like a bit of a convoluted way to set the damage of ShipManager:DamageBeam, but eh, not my code.

**Comment by Nasa62** [comment]
Added your example to the Wiki, thanks
