### ISSUE TITLE
Electrical shock

### ISSUE THREAD

**Issue by adaneslavo** [FTL-Hyperspace/FTL-Hyperspace#65]
[Expansion]

This might involve huge work, but did you think of adding electrical shock as a potential new cause of dmg/stun? F.e. Crew in damaged room that still is operating could be stunned at random intervals with some small dmg. Also entering or leaving such room could have small chance.

This could be used for some crew perks or resistances. Also some augments.

Random intervals and high stun values would be characteristical for this source of dmg.

**Comment by Nasa62** [comment]
Probably will never happen in Hyperspace directly but it may be possible for mods to add an effect like this in the future with Lua by drawing the animation on screen & simply hurting the crew.
