### ISSUE TITLE
Expand WAIT beacon option

### ISSUE THREAD

**Issue by adaneslavo** [FTL-Hyperspace/FTL-Hyperspace#66]
[Expansion]

Now you cannot do WAIT if you have fuel on your ship or dont fight the flagship. It's strange when you are ahead of the fleet, arrive at Exit beacon and have no beacons left and what would you want to do is gather some stuff before jump, just stanting in the beacon until fleet arrives.

**Comment by Nasa62** [comment]
I don't think this is something for Hyperspace, this is something for other mods to add if they wish to (as there would be balance concerns) they could potentially add a button in a future version with Lua when on an exit beacon if so desired.

**Comment by adaneslavo** [comment]
Is this possible for MV to add it without Hyperspace intervention?
