### ISSUE TITLE
Automatically set default renderer based on GPU vendor for Windows

### ISSUE THREAD

**Issue by mathchamp93** [FTL-Hyperspace/FTL-Hyperspace#69]
Currently Hyperspace forces FTL to default to Direct3D for the rendering API in Windows due to compatibility/memory issues with large mods. However, the compatibility is dependent on the GPU vendor/driver:

- NVIDIA: Works better with Direct3D.
- AMD: Works with either.
- Intel: Works better with OpenGL.

Currently players using Intel cards can override the choice but it would be good for Hyperspace to manage this automatically.

Possible solutions that could be implemented:

- Use parts of the Windows API to determine the GPU vendor (it's okay to use Windows API for this since this is Windows-specific; the code shall not be included when building for Linux).
- Allow the game to initialize either rendering API, use that API (via hook) to determine the GPU vendor, save a file that contains a flag that will tell Hyperspace which API to select next time (do all this early enough before resources get loaded and the game potentially crashes). If a possible incompatibility is detected then also pop up a warning message to inform the user of the issue and that the default will be switched on next startup. This is okay but it means that some users may need to load the game twice the first time they use Hyperspace.
- Create a dummy OpenGL context, use it to get the GPU vendor info, then destroy it.

**Comment by Nasa62** [comment]
I'm not 100% sure on the Intel front. I think there might be some bad Intel models/driver combos that need DirectX.

We should default to OpenGL on Intel but we probably do need a `--directx` option unless we can identify those problematic cards

**Comment by Nasa62** [comment]
And who knows about the new Arc GPUs

**Comment by adaneslavo** [comment]
For me OpenGL is not working. Will potential auto-detect verify that?

**Comment by Nasa62** [comment]
> For me OpenGL is not working. Will potential auto-detect verify that?

Auto Detect will just change between OpenGL or DirectX rendering modes based on your GPU vendor. If it's Nvidia we'll use DirectX, all others we'll switch to OpenGL

**Comment by Nasa62** [comment]
> * Create a dummy OpenGL context, use it to get the GPU vendor info, then destroy it.

I don't think you have to create a dummy context, look in Ghidra at some of the initialization stuff shortly after `main` & `sil_main` I think it is, if I find it I'll post here but there's a method where FTL actually loads both (it's the same place where we change to opengl currently with the launch argument I think) and so you have handles to both OpenGL & DirectX APIs you could then use either to see the GPU vendor (in fact I think this is also where FTL prints out the renderer to the log)
