### ISSUE TITLE
Need to rewrite ASB icon to support Neutral ASB

### ISSUE THREAD

**Issue by Nasa62** [FTL-Hyperspace/FTL-Hyperspace#84]
The ASB Icon & associated text is inconsistent.
![image](https://user-images.githubusercontent.com/1423894/221954999-81a47c40-b958-4da5-82b3-d433b1838eee.png)

Additionally we can't have both ALLIED & ENEMY ASB icons up at the same time due to the way the game hardcodes the struct for it. There is actually a possibility of a Neutral ASB logo but the game's internal implementation it's impossible to use. We would need to reverse engineer the original implementation of the render function for status effects so that we can support all 3 states (and maybe other custom status icons)

**Comment by ChronoVortex** [comment]
Adding this here - looks like the function that handles this is `SpaceStatus::RenderWarningText`
